paths:
  - 'D:/qwwork/idletowera/tools/ExceltoBytes/out/server/bytes'
db_name: game_config_data
# type:1 本地  2 远程  3 本地和远程都更新
type: 3
databases:
  local:
    db_port: 3307
    db_host: 127.0.0.1
    db_user: root
    db_pass: 123456
  remote:
    db_port: 3306
    db_host: 192.168.50.3
    db_user: root
    db_pass: 123456
db_url_params: charset=utf8
group: ccj